### ISSUE TITLE
Document how to get the basic python packages in Linux, MAC OS and Windows

### ISSUE THREAD

**Issue by fccoelho** [Mosqlimate-project/sprint-template#6]
In order to use mosqlient, the user's operating system must have the basic python packages installed.

On a debian-based system, they would be at least: 

```bash
apt install python3-dev jupyter python3-venv python3-pip
```

anything else?

For Mac, @eduardocorrearaujo can you tell?

for windows a basic anaconda install will do.

this info needs to be added to the README

**Comment by eduardocorrearaujo** [comment]
In Mac, if a user has a [miniforge](https://github.com/conda-forge/miniforge) or anaconda install, he can simply install the packages using conda install. To install pip, it is just necessary to use `conda install pip`. I think that's the most common use in Mac. 

Wouldn't it be better to create a `pyproject. toml` file for the Python users?

**Comment by fccoelho** [comment]
Ihad though this wouldn't be necessary but in order to make it as easy as possible let's do the `pyproject.toml`

I'll add the equivalent for R.
